# Generated by Django 4.2.2 on 2023-07-28 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_role',
            field=models.CharField(choices=[('ADMINISTRATOR', 'Administrator'), ('MANAGER', 'Project manager'), ('STAFF', 'Staff')], default='STAFF', max_length=50),
        ),
    ]
