# Generated by Django 4.2.2 on 2023-07-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersprofile',
            name='user',
        ),
    ]
