# Generated by Django 4.2.2 on 2023-07-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authAPI', '0002_alter_userauthentiacation_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsersProfile',
        ),
    ]
